"use client";

import { useEffect, useRef, useState } from "react";
import { useLocale } from "@/i18n/locale";
import { getSupabase } from "@/lib/supabase";
import {
  aiReviewSuggestion,
  isAdoptableSuggestion,
  reviewedPayloadPreview,
  type AiAdoptionMetadata,
} from "@/lib/ai-reviewed-summary";
import {
  AI_CONTRACT_VERSION,
  aiRequestPrivacyIssues,
  parseAiAssistRequest,
  parseAiReviewResponse,
  type AiAssistRequest,
  type AiReviewResponse,
} from "@/lib/ai-contract";
type Result = {
  request: AiAssistRequest;
  review: AiReviewResponse;
  sourceRevision: string;
  metadata: AiAdoptionMetadata;
};

type AdoptionHandler = (
  review: AiReviewResponse,
  metadata: AiAdoptionMetadata,
  submittedRequest: AiAssistRequest,
) => boolean | void | Promise<boolean | void>;

function copy(locale: "de" | "en") {
  return locale === "en"
    ? {
        eyebrow: "AI analysis coach",
        intro:
          "Get a structured second opinion on this field—without giving the model control of your QCA.",
        step1: "Review what will be shared",
        step2: "Send only after you approve",
        step3: "Apply or discard the suggestion yourself",
        review:
          "This is the exact payload. It is checked locally for row-like data, contact identifiers, and current case labels before it can be sent.",
        preview: "Request preview",
        prepare: "Prepare AI review",
        send: "Send to AI coach",
        noRows: "No dataset rows in this request",
        busy: "Analyzing…",
        applying: "Applying…",
        status: "Review status",
        reviewLabel: "Assessment",
        suggestion: "Suggested replacement",
        uncertainty: "Uncertainty",
        evidence: "Evidence to add",
        limitations: "Method limits",
        provider: "Generated by",
        network: "The request could not be sent.",
        invalid: "The service returned an invalid response.",
        missing:
          "Complete every required field and keep each entry within 2,000 characters before preparing an AI review.",
        privacy:
          "Remove dataset rows, contact details, and case identifiers before preparing an AI review.",
        discard: "Discard suggestion",
        discarded: "The suggestion was discarded.",
        adopted: "The suggestion was applied. Review and confirm the field yourself.",
        adoptionFailed:
          "The source field changed or provenance could not be recorded. Prepare a fresh review before applying it.",
        sourceChanged:
          "The reviewed source changed. Prepare a fresh request before applying a suggestion.",
        unavailable:
          "AI review is unavailable on this deployment. You can continue the analysis without it.",
      }
    : {
        eyebrow: "KI-Analysecoach",
        intro:
          "Holen Sie eine strukturierte Zweitprüfung zu diesem Feld ein – ohne der KI Kontrolle über Ihre QCA zu geben.",
        step1: "Prüfen, was geteilt wird",
        step2: "Erst nach Freigabe senden",
        step3: "Vorschlag selbst übernehmen oder verwerfen",
        review:
          "Dies ist die exakte Nutzlast. Vor dem Versand wird sie lokal auf zeilenartige Daten, Kontaktdaten und aktuelle Fallkennungen geprüft.",
        preview: "Anfragevorschau",
        prepare: "KI-Prüfung vorbereiten",
        send: "An KI-Coach senden",
        noRows: "Keine Datensatzzeilen in dieser Anfrage",
        busy: "Analyse läuft…",
        applying: "Wird übernommen…",
        status: "Prüfstatus",
        reviewLabel: "Einordnung",
        suggestion: "Vorgeschlagener Ersatz",
        uncertainty: "Unsicherheit",
        evidence: "Noch benötigte Evidenz",
        limitations: "Methodische Grenzen",
        provider: "Erstellt mit",
        network: "Die Anfrage konnte nicht gesendet werden.",
        invalid: "Der Dienst hat keine gültige Antwort geliefert.",
        missing:
          "Füllen Sie alle erforderlichen Felder aus und begrenzen Sie jeden Eintrag auf 2.000 Zeichen, bevor Sie eine KI-Prüfung vorbereiten.",
        privacy:
          "Entfernen Sie Datensatzzeilen, Kontaktdaten und Fallkennungen, bevor Sie eine KI-Prüfung vorbereiten.",
        discard: "Vorschlag verwerfen",
        discarded: "Der Vorschlag wurde verworfen.",
        adopted:
          "Der Vorschlag wurde übernommen. Prüfen und bestätigen Sie das Feld anschließend selbst.",
        adoptionFailed:
          "Das Ausgangsfeld wurde geändert oder die Provenienz konnte nicht erfasst werden. Bereiten Sie vor der Übernahme eine neue Prüfung vor.",
        sourceChanged:
          "Die geprüfte Ausgangslage wurde geändert. Bereiten Sie vor einer Übernahme eine neue Anfrage vor.",
        unavailable:
          "Die KI-Prüfung ist in dieser Bereitstellung nicht verfügbar. Sie können die Analyse ohne sie fortsetzen.",
      };
}

function list(items: string[]) {
  return (
    <ul>
      {items.map((item, index) => (
        <li key={`${index}-${item}`}>{item}</li>
      ))}
    </ul>
  );
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function errorMessage(value: unknown): string | null {
  if (!isRecord(value) || !isRecord(value.error)) return null;
  return typeof value.error.message === "string" ? value.error.message : null;
}

function suggestionLabel(task: AiAssistRequest["task"], locale: "de" | "en"): string {
  if (task === "brief_clarify") {
    return locale === "en" ? "Suggested research question" : "Vorgeschlagene Forschungsfrage";
  }
  if (task === "calibration_evidence_gaps") {
    return locale === "en" ? "Suggested set definition" : "Vorgeschlagene Set-Definition";
  }
  return locale === "en" ? "Suggested rationale" : "Vorgeschlagene Begründung";
}

function adoptLabel(task: AiAssistRequest["task"], locale: "de" | "en"): string {
  if (task === "brief_clarify") {
    return locale === "en" ? "Use suggested question" : "Vorgeschlagene Frage verwenden";
  }
  if (task === "calibration_evidence_gaps") {
    return locale === "en"
      ? "Use suggested definition"
      : "Vorgeschlagene Definition verwenden";
  }
  return locale === "en"
    ? "Use suggested rationale"
    : "Vorgeschlagene Begründung verwenden";
}
const NO_SENSITIVE_VALUES: readonly string[] = [];

export function AiAssist({
  request,
  label,
  sourceRevision,
  sensitiveValues = NO_SENSITIVE_VALUES,
  focusTargetId,
  onAdopt,
}: {
  request: () => AiAssistRequest;
  label: string;
  sourceRevision?: () => string;
  sensitiveValues?: readonly string[];
  focusTargetId?: string;
  onAdopt?: AdoptionHandler;
}) {
  const [locale] = useLocale();
  const text = copy(locale);
  const [prepared, setPrepared] = useState<AiAssistRequest | null>(null);
  const [busy, setBusy] = useState(false);
  const [applying, setApplying] = useState(false);
  const [result, setResult] = useState<Result | null>(null);
  const [note, setNote] = useState<string | null>(null);
  const [available, setAvailable] = useState<boolean | null>(null);
  const [invalidPayload, setInvalidPayload] = useState(false);
  const rootRef = useRef<HTMLElement>(null);
  const previewRef = useRef<HTMLDivElement>(null);
  const resultRef = useRef<HTMLDivElement>(null);
  const preparedRevisionRef = useRef("");
  const requestRef = useRef(request);
  const sourceRevisionRef = useRef(sourceRevision);
  const triggerRef = useRef<HTMLButtonElement>(null);
  const sensitiveValuesRef = useRef(sensitiveValues);

  function requestSignature(value: AiAssistRequest): string {
    return JSON.stringify(value);
  }

  function currentSourceRevision(): string {
    return sourceRevisionRef.current?.() ?? "";
  }

  function currentRequest(): AiAssistRequest {
    return requestRef.current();
  }

  function focusAfterRender(targetId?: string): void {
    window.setTimeout(() => {
      const target = targetId ? document.getElementById(targetId) : null;
      if (target instanceof HTMLElement) target.focus();
      else triggerRef.current?.focus();
    }, 0);
  }

  useEffect(() => {
    requestRef.current = request;
    sourceRevisionRef.current = sourceRevision;
    sensitiveValuesRef.current = sensitiveValues;
  }, [request, sensitiveValues, sourceRevision]);

  useEffect(() => {
    const controller = new AbortController();
    fetch("/api/ai/status", { cache: "no-store", signal: controller.signal })
      .then(async (response) => {
        if (!response.ok) return false;
        const payload: unknown = await response.json();
        if (typeof payload !== "object" || payload === null || Array.isArray(payload)) return false;
        return "available" in payload && payload.available === true;
      })
      .then((nextAvailable) => setAvailable(nextAvailable))
      .catch((error: unknown) => {
        if (error instanceof DOMException && error.name === "AbortError") return;
        setAvailable(false);
      });
    return () => controller.abort();
  }, []);

  useEffect(() => {
    if (result) {
      resultRef.current?.focus();
      return;
    }
    if (prepared) previewRef.current?.focus();
  }, [prepared, result]);

  useEffect(() => {
    if (applying) return;
    const submitted = result?.request ?? prepared;
    if (!submitted) return;
    const current = parseAiAssistRequest(request());
    const restoreAiFocus = rootRef.current?.contains(document.activeElement) === true;
    if (
      current &&
      aiRequestPrivacyIssues(current, sensitiveValuesRef.current).length === 0 &&
      requestSignature(current) === requestSignature(submitted) &&
      (result?.sourceRevision ?? preparedRevisionRef.current) === (sourceRevision?.() ?? "")
    ) return;
    setResult(null);
    setPrepared(null);
    setNote(text.sourceChanged);
    if (restoreAiFocus) focusAfterRender();
  }, [applying, prepared, request, result, sourceRevision, text.sourceChanged]);

  function prepare() {
    const requested = currentRequest();
    setResult(null);
    if (aiRequestPrivacyIssues(requested, sensitiveValuesRef.current).length > 0) {
      setPrepared(null);
      setNote(text.privacy);
      setInvalidPayload(false);
      return;
    }
    const candidate = parseAiAssistRequest(requested);
    if (!candidate) {
      setPrepared(null);
      setNote(null);
      setInvalidPayload(true);
      return;
    }
    const revision = currentSourceRevision();
    setNote(null);
    setInvalidPayload(false);
    setPrepared(candidate);
    preparedRevisionRef.current = revision;
  }

  async function send() {
    if (!prepared) return;
    if (aiRequestPrivacyIssues(prepared, sensitiveValuesRef.current).length > 0) {
      setPrepared(null);
      setNote(text.privacy);
      return;
    }
    const submitted = prepared;
    const submittedRevision = preparedRevisionRef.current;
    setBusy(true);
    setResult(null);
    setNote(null);
    try {
      const sb = getSupabase();
      const { data } = (await sb?.auth.getSession()) ?? { data: null };
      const headers: Record<string, string> = { "Content-Type": "application/json" };
      if (data?.session?.access_token) headers.Authorization = `Bearer ${data.session.access_token}`;
      const response = await fetch("/api/ai/assist", {
        method: "POST",
        headers,
        body: JSON.stringify(submitted),
      });
      const json: unknown = await response.json().catch(() => null);
      const review = isRecord(json) ? parseAiReviewResponse(json.review, submitted) : null;
      const generatedAt =
        isRecord(json) && typeof json.generatedAt === "string" ? json.generatedAt : "";
      const model = isRecord(json) && typeof json.model === "string" ? json.model : "";
      const provider = isRecord(json) && typeof json.provider === "string" ? json.provider : "";
      const validMetadata =
        model.trim() &&
        provider.trim() &&
        generatedAt &&
        !Number.isNaN(Date.parse(generatedAt));
      if (
        response.ok &&
        isRecord(json) &&
        json.version === AI_CONTRACT_VERSION &&
        review &&
        validMetadata
      ) {
        const current = parseAiAssistRequest(currentRequest());
        if (
          !current ||
          requestSignature(current) !== requestSignature(submitted) ||
          submittedRevision !== currentSourceRevision()
        ) {
          setPrepared(null);
          setNote(text.sourceChanged);
          focusAfterRender();
          return;
        }
        setResult({
          request: submitted,
          review,
          sourceRevision: submittedRevision,
          metadata: { model, provider, generatedAt },
        });
      } else {
        setNote(errorMessage(json) ?? text.invalid);
      }
    } catch {
      setNote(text.network);
    } finally {
      setBusy(false);
    }
  }

  async function adopt() {
    if (!result || !onAdopt || !isAdoptableSuggestion(result.review)) return;
    if (result.sourceRevision !== currentSourceRevision()) {
      setResult(null);
      setPrepared(null);
      setNote(text.sourceChanged);
      focusAfterRender();
      return;
    }
    setApplying(true);
    setNote(null);
    try {
      const adopted = await onAdopt(result.review, result.metadata, result.request);
      if (adopted === false) {
        setNote(text.adoptionFailed);
        return;
      }
      setResult(null);
      setPrepared(null);
      setNote(text.adopted);
      focusAfterRender(focusTargetId);
    } catch {
      setNote(text.adoptionFailed);
    } finally {
      setApplying(false);
    }
  }

  function discard() {
    setResult(null);
    setPrepared(null);
    setNote(text.discarded);
    focusAfterRender();
  }

  const activeStep = result ? 3 : prepared ? 2 : 1;
  const status =
    result?.review.status === "ok"
      ? locale === "en"
        ? "ready for your review"
        : "bereit für Ihre Prüfung"
      : result?.review.status === "incomplete"
        ? locale === "en"
          ? "needs more context"
          : "benötigt mehr Kontext"
        : locale === "en"
          ? "request declined"
          : "Anfrage abgelehnt";
  const suggestion = result ? aiReviewSuggestion(result.review) : "";

  return (
    <section
      ref={rootRef}
      className="oq-ai-assist"
      aria-label={label}
      aria-busy={busy || applying}
    >
      <div className="oq-ai-assist__header">
        <div>
          <span className="oq-ai-assist__eyebrow">{text.eyebrow}</span>
          <h3>{label}</h3>
          <p>{text.intro}</p>
        </div>
        <span className="oq-ai-assist__boundary">
          {locale === "en" ? "Advisory only" : "Nur beratend"}
        </span>
      </div>
      <ol className="oq-ai-assist__steps" aria-label={locale === "en" ? "AI review progress" : "Fortschritt der KI-Prüfung"}>
        {[text.step1, text.step2, text.step3].map((step, index) => {
          const number = index + 1;
          return (
            <li
              key={step}
              aria-current={activeStep === number ? "step" : undefined}
              data-state={activeStep > number ? "complete" : activeStep === number ? "current" : "upcoming"}
            >
              {step}
            </li>
          );
        })}
      </ol>
      {available === false && (
        <p className="oq-ai-assist__note" role="status">
          {text.unavailable}
        </p>
      )}
      {available === true && !prepared && !result && (
        <button
          ref={triggerRef}
          type="button"
          className="oq-btn oq-ai-assist__trigger"
          onClick={prepare}
          disabled={busy || applying}
        >
          {text.prepare}
        </button>
      )}
      {available === true && prepared && !result && (
        <div
          ref={previewRef}
          className="oq-ai-assist__preview"
          role="region"
          aria-label={text.preview}
          tabIndex={-1}
        >
          <div className="oq-ai-assist__preview-head">
            <strong>{text.preview}</strong>
            <span>{text.noRows}</span>
          </div>
          <p>{text.review}</p>
          <dl>
            {reviewedPayloadPreview(prepared).map((item) => (
              <div key={item.label}>
                <dt>{item.label}</dt>
                <dd>{item.value}</dd>
              </div>
            ))}
          </dl>
          <button
            type="button"
            className="oq-btn oq-btn--primary"
            onClick={() => void send()}
            disabled={busy || applying}
          >
            {busy ? text.busy : text.send}
          </button>
        </div>
      )}
      {(invalidPayload || note) && (
        <p className="oq-ai-assist__note" role="status" aria-live="polite">
          {invalidPayload ? text.missing : note}
        </p>
      )}
      {result && (
        <div
          ref={resultRef}
          className="oq-ai-assist__result"
          role="region"
          aria-label={`${text.status}: ${status}`}
          aria-live="polite"
          tabIndex={-1}
        >
          <div className="oq-ai-assist__result-head">
            <strong>{text.status}</strong>
            <span>{status}</span>
          </div>
          {result.review.review && (
            <div>
              <strong>{text.reviewLabel}</strong>
              <div className="oq-ai-assist__text">{result.review.review}</div>
            </div>
          )}
          {suggestion && (
            <div>
              <strong>{suggestionLabel(result.request.task, locale)}</strong>
              <div className="oq-ai-assist__text">{suggestion}</div>
            </div>
          )}
          {result.review.uncertainty.length > 0 && (
            <div>
              <strong>{text.uncertainty}</strong>
              {list(result.review.uncertainty)}
            </div>
          )}
          {result.review.evidenceNeeds.length > 0 && (
            <div>
              <strong>{text.evidence}</strong>
              {list(result.review.evidenceNeeds)}
            </div>
          )}
          {result.review.limitations.length > 0 && (
            <div>
              <strong>{text.limitations}</strong>
              {list(result.review.limitations)}
            </div>
          )}
          <p>
            <strong>{text.provider}:</strong> {result.metadata.provider} · {result.metadata.model}
          </p>
          <div className="oq-action-row">
            {onAdopt && isAdoptableSuggestion(result.review) && (
              <button
                type="button"
                className="oq-btn oq-btn--primary"
                onClick={() => void adopt()}
                disabled={applying}
              >
                {applying ? text.applying : adoptLabel(result.request.task, locale)}
              </button>
            )}
            <button type="button" className="oq-btn" onClick={discard} disabled={applying}>
              {text.discard}
            </button>
          </div>
        </div>
      )}
    </section>
  );
}
