"use client";

import { useState } from "react";
import { useLocale } from "@/i18n/locale";
import { getSupabase } from "@/lib/supabase";
import { isAdoptableDraft, reviewedPayloadPreview } from "@/lib/ai-reviewed-summary";
import { parseAiAssistRequest, parseReviewedSummary, type AiAssistRequest, type ReviewedSummary } from "@/lib/ai-contract";

type Result = { summary: ReviewedSummary; model: string; provider: string };

function copy(locale: "de" | "en") {
  return locale === "en" ? {
    eyebrow: "AI analysis coach",
    intro: "Get a structured second opinion on this part of your analysis—without giving the model control of your QCA.",
    step1: "Review what will be shared",
    step2: "Send only after you approve",
    step3: "Accept or reject the draft yourself",
    review: "This is the exact payload. Dataset rows are not added automatically. Free-text fields are sent exactly as shown and may contain sensitive case information.",
    preview: "Request preview",
    prepare: "Prepare AI review",
    send: "Send to AI coach",
    noRows: "No dataset rows added",
    busy: "Analyzing…",
    status: "Review status",
    uncertainty: "Uncertainty",
    evidence: "Evidence to add",
    limitations: "Method limits",
    provider: "Generated by",
    network: "The request could not be sent.",
    invalid: "The service returned an invalid response.",
    missing: "Complete every required field and keep each entry within 2,000 characters before preparing an AI review.",
  } : {
    eyebrow: "KI-Analysecoach",
    intro: "Holen Sie eine strukturierte Zweitprüfung zu diesem Teil Ihrer Analyse ein – ohne der KI Kontrolle über Ihre QCA zu geben.",
    step1: "Prüfen, was geteilt wird",
    step2: "Erst nach Freigabe senden",
    step3: "Entwurf selbst annehmen oder verwerfen",
    review: "Dies ist die exakte Nutzlast. Datensatzzeilen werden nicht automatisch hinzugefügt. Freitextfelder werden exakt wie angezeigt gesendet und können sensible Fallinformationen enthalten.",
    preview: "Anfragevorschau",
    prepare: "KI-Prüfung vorbereiten",
    send: "An KI-Coach senden",
    noRows: "Keine Datensatzzeilen hinzugefügt",
    busy: "Analyse läuft…",
    status: "Prüfstatus",
    uncertainty: "Unsicherheit",
    evidence: "Noch benötigte Evidenz",
    limitations: "Methodische Grenzen",
    provider: "Erstellt mit",
    network: "Die Anfrage konnte nicht gesendet werden.",
    invalid: "Der Dienst hat keine gültige Antwort geliefert.",
    missing: "Füllen Sie alle erforderlichen Felder aus und begrenzen Sie jeden Eintrag auf 2.000 Zeichen, bevor Sie eine KI-Prüfung vorbereiten.",
  };
}

function list(items: string[]) {
  return <ul>{items.map((item, index) => <li key={`${index}-${item}`}>{item}</li>)}</ul>;
}

export function AiAssist({ request, label, onAdopt }: { request: () => AiAssistRequest; label: string; onAdopt?: (draft: string) => void }) {
  const [locale] = useLocale();
  const text = copy(locale);
  const [prepared, setPrepared] = useState<AiAssistRequest | null>(null);
  const [busy, setBusy] = useState(false);
  const [result, setResult] = useState<Result | null>(null);
  const [note, setNote] = useState<string | null>(null);
  const [invalidPayload, setInvalidPayload] = useState(false);

  function prepare() {
    const candidate = parseAiAssistRequest(request());
    setResult(null);
    if (!candidate) {
      setPrepared(null);
      setNote(null);
      setInvalidPayload(true);
      return;
    }
    setPrepared(candidate);
    setNote(null);
    setInvalidPayload(false);
  }

  async function send() {
    if (!prepared) return;
    setBusy(true);
    setResult(null);
    setNote(null);
    try {
      const sb = getSupabase();
      const { data } = (await sb?.auth.getSession()) ?? { data: null };
      const headers: Record<string, string> = { "Content-Type": "application/json" };
      if (data?.session?.access_token) headers.Authorization = `Bearer ${data.session.access_token}`;
      const response = await fetch("/api/ai/assist", { method: "POST", headers, body: JSON.stringify(prepared) });
      const json = await response.json().catch(() => null) as { summary?: unknown; model?: unknown; provider?: unknown; error?: { message?: unknown } } | null;
      const summary = parseReviewedSummary(json?.summary);
      if (response.ok && summary && typeof json?.model === "string" && typeof json.provider === "string") {
        setResult({ summary, model: json.model, provider: json.provider });
      } else {
        setNote(typeof json?.error?.message === "string" ? json.error.message : text.invalid);
      }
    } catch {
      setNote(text.network);
    } finally {
      setBusy(false);
    }
  }

  const status = result?.summary.status === "ok"
    ? (locale === "en" ? "ready for your review" : "bereit für Ihre Prüfung")
    : result?.summary.status === "incomplete"
      ? (locale === "en" ? "needs more context" : "benötigt mehr Kontext")
      : (locale === "en" ? "request declined" : "Anfrage abgelehnt");
  const adoptLabel = prepared?.task === "brief_clarify"
    ? (locale === "en" ? "Replace research question" : "Forschungsfrage ersetzen")
    : prepared?.task === "calibration_evidence_gaps"
      ? (locale === "en" ? "Replace set definition" : "Set-Definition ersetzen")
      : (locale === "en" ? "Replace rationale" : "Begründung ersetzen");

  return (
    <section className="oq-ai-assist" aria-label={label}>
      <div className="oq-ai-assist__header">
        <div>
          <span className="oq-ai-assist__eyebrow">{text.eyebrow}</span>
          <h3>{label}</h3>
          <p>{text.intro}</p>
        </div>
        <span className="oq-ai-assist__boundary">{locale === "en" ? "Advisory only" : "Nur beratend"}</span>
      </div>
      <ol className="oq-ai-assist__steps">
        <li>{text.step1}</li>
        <li>{text.step2}</li>
        <li>{text.step3}</li>
      </ol>
      <button type="button" className="oq-btn oq-ai-assist__trigger" onClick={prepare} disabled={busy}>{text.prepare}</button>
      {prepared && (
        <div className="oq-ai-assist__preview">
          <div className="oq-ai-assist__preview-head"><strong>{text.preview}</strong><span>{text.noRows}</span></div>
          <p>{text.review}</p>
          <dl>{reviewedPayloadPreview(prepared).map((item) => <div key={item.label}><dt>{item.label}</dt><dd>{item.value}</dd></div>)}</dl>
          <button type="button" className="oq-btn oq-btn--primary" onClick={() => void send()} disabled={busy}>{busy ? text.busy : text.send}</button>
        </div>
      )}
      <p className="oq-ai-assist__note" role="status" aria-live="polite">{invalidPayload ? text.missing : note}</p>
      {result && (
        <div className="oq-ai-assist__result">
          <div className="oq-ai-assist__result-head"><strong>{text.status}</strong><span>{status}</span></div>
          {result.summary.draft && <div className="oq-ai-assist__text">{result.summary.draft}</div>}
          {result.summary.uncertainty.length > 0 && <div><strong>{text.uncertainty}</strong>{list(result.summary.uncertainty)}</div>}
          {result.summary.evidenceNeeds.length > 0 && <div><strong>{text.evidence}</strong>{list(result.summary.evidenceNeeds)}</div>}
          {result.summary.limitations.length > 0 && <div><strong>{text.limitations}</strong>{list(result.summary.limitations)}</div>}
          <p><strong>{text.provider}:</strong> {result.provider} · {result.model}</p>
          {onAdopt && isAdoptableDraft(result.summary) && <button type="button" className="oq-btn oq-btn--primary" onClick={() => onAdopt(result.summary.draft)}>{adoptLabel}</button>}
        </div>
      )}
    </section>
  );
}
