/**
 * Reproducible calibration / analysis protocol exports (JSON, Markdown, R).
 */

import type { RawDataset } from "@/lib/demo";
import {
  calibrationReadiness,
  directThresholds,
  effectiveStatus,
  type CalibSpecs,
  type CalibrationDecisionStatus,
  type CalibrationSpec,
  type EvidenceTarget,
  type EvidenceType,
  type VarType,
} from "@/lib/calibration-model";
import { t, type DictKey } from "@/i18n/dict";
import type { CombinedRobustnessResult } from "@openqca/engine";
import type {
  CalibrationEvaluation,
  CalibrationSensitivityResultWithRows,
  SensitivityBundle,
} from "@/lib/calibration-analysis";

export type VarMeta = { type: VarType; role: "condition" | "outcome" | "ignore" };
export type MethodologyReference = {
  id: string;
  citation: string;
  doi?: string;
  url: string;
  pages?: string;
  scope: string;
};

const TOOL_VERSION = "0.0.0";
export const RAW_DATA_FILENAME = "openqca-raw-data.csv";
export const METHODOLOGY_REFERENCES: readonly MethodologyReference[] = [
  {
    id: "ragin-2008",
    citation: "Charles C. Ragin (2008), Redesigning Social Inquiry: Fuzzy Sets and Beyond, University of Chicago Press",
    doi: "10.7208/chicago/9780226702797.001.0001",
    url: "https://doi.org/10.7208/chicago/9780226702797.001.0001",
    scope: "Fuzzy-set calibration and the distinction between calibration and measurement",
  },
  {
    id: "schneider-wagemann-2012",
    citation: "Carsten Q. Schneider and Claudius Wagemann (2012), Set-Theoretic Methods for the Social Sciences, Cambridge University Press",
    doi: "10.1017/CBO9781139004244",
    url: "https://doi.org/10.1017/CBO9781139004244",
    pages: "35–36",
    scope: "Chapter 4, calibration and substantive qualitative anchors",
  },
  {
    id: "dusa-2019",
    citation: "Adrian Dușa (2019), QCA with R: A Comprehensive Resource, Springer",
    doi: "10.1007/978-3-319-75668-4",
    url: "https://doi.org/10.1007/978-3-319-75668-4",
    scope: "QCA workflows and the QCA package",
  },
  {
    id: "oana-schneider-2022",
    citation: "Ioana-Elena Oana and Carsten Q. Schneider (2022), A Robustness Test for Qualitative Comparative Analysis (QCA)",
    doi: "10.1177/00491241211036158",
    url: "https://doi.org/10.1177/00491241211036158",
    pages: "603–638",
    scope: "Sensitivity analysis for calibration, thresholds, cases, and model specifications",
  },
  {
    id: "qca-manual-3-25",
    citation: "Adrian Dușa, QCA package reference manual v3.25",
    url: "https://cran.r-project.org/web/packages/QCA/QCA.pdf",
    pages: "4–8",
    scope: "Official calibrate() reference",
  },
] as const;

export function buildRawCsv(ds: RawDataset): string {
  const cell = (value: unknown): string => {
    const text = value == null ? "" : String(value);
    return /[",\r\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text;
  };
  return [
    ds.columns.map(cell).join(","),
    ...ds.rows.map((row) => ds.columns.map((column) => cell(row[column])).join(",")),
  ].join("\n") + "\n";
}

function commentLines(text: string): string[] {
  return text
    .split("\n")
    .map((l) => `# ${l}`);
}

function rString(value: string): string {
  return JSON.stringify(value);
}

function rColumnRef(dataFrame: string, column: string): string {
  return `${dataFrame}[[${rString(column)}]]`;
}

function rConditions(columns: string[]): string {
  return `c(${columns.map(rString).join(", ")})`;
}

function rIdentifier(value: string, fallback: string): string {
  const safe = value.replace(/[^A-Za-z0-9_]/g, "_").replace(/^(\d)/, "_$1");
  return safe || fallback;
}

export function buildRScript(args: {
  ds: RawDataset;
  calibSpecs: CalibSpecs;
  varMeta: Record<string, VarMeta>;
  conditions: string[];
  sensitivity?: SensitivityBundle;
  robustness?: CombinedRobustnessResult | null;
  outcome: string;
  freqCut: number;
  consCut: number;
}): string {
  const { calibSpecs, varMeta, conditions, outcome, freqCut, consCut, sensitivity, robustness } = args;
  const lines: string[] = [
    "# openQCA → R (package QCA)",
    `# Generated by openQCA ${TOOL_VERSION}`,
    "# Direct fuzzy uses logistic = TRUE to approximate Ragin (2008) direct calibration.",
    "# Engine fixed points at anchors are ≈0.0474 / 0.50 / 0.9526 (log-odds ±3).",
    "# R QCA logistic targets ≈0.05 / 0.50 / 0.95; the documented residual is expected.",
    "# Substantive calibration evidence is recorded below; empirical diagnostics are not proof.",
    ...METHODOLOGY_REFERENCES.flatMap((reference) =>
      commentLines(
        `${reference.citation}. ${reference.url}${reference.pages ? `; pages ${reference.pages}` : ""}`,
      ),
    ),
    "# After running: sessionInfo()",
    "",
    "library(QCA)",
    "",
    `raw_data <- read.csv(${rString(RAW_DATA_FILENAME)}, check.names = FALSE, na.strings = c("", "NA"))`,
    "df <- raw_data",
    "parse_openqca_number <- function(x) {",
    "  text <- trimws(as.character(x))",
    "  comma_decimal <- grepl(\",\", text, fixed = TRUE) & !grepl(\".\", text, fixed = TRUE)",
    "  text[comma_decimal] <- sub(\",\", \".\", text[comma_decimal], fixed = TRUE)",
    "  suppressWarnings(as.numeric(text))",
    "}",
    "",
    "",
  ];

  const rawNameCounts: Record<string, number> = {};
  const analysisColumns = [...new Set([...conditions, outcome])];
  const invalidActiveRawColumns = new Set<string>();
  for (const col of Object.keys(varMeta)) {
    const meta = varMeta[col];
    if (!meta || meta.role === "ignore") continue;
    const isAnalysisColumn = analysisColumns.includes(col);
    const spec = calibSpecs[col];
    if (!spec) {
      if (meta.type === "raw" && isAnalysisColumn) invalidActiveRawColumns.add(col);
      continue;
    }
    const fuzzyAnchors =
      spec.method === "direct" ? spec.direct : spec.method === "linear" ? spec.linear : undefined;
    const rawCalibrationValid =
      meta.type !== "raw" ||
      ((spec.method === "direct" || spec.method === "linear") &&
        !!directThresholds(fuzzyAnchors, spec.set.highIsMembership)) ||
      (spec.method === "crisp" && !!spec.crisp && Number.isFinite(spec.crisp.threshold));
    if (meta.type === "raw" && isAnalysisColumn && !rawCalibrationValid) {
      invalidActiveRawColumns.add(col);
    }
    const rawBase = `raw_${rIdentifier(col, "column")}`;
    rawNameCounts[rawBase] = (rawNameCounts[rawBase] ?? 0) + 1;
    const rawName =
      rawNameCounts[rawBase] === 1 ? rawBase : `${rawBase}_${rawNameCounts[rawBase]}`;
    const colRef = rColumnRef("df", col);

    lines.push(...commentLines(`Set: ${spec.set.setLabel || col} (${meta.role})`));
    if (spec.set.definition) lines.push(...commentLines(`Definition: ${spec.set.definition}`));
    lines.push(...commentLines(`Unit: ${spec.set.unit || "not recorded"}`));
    lines.push(...commentLines(`Scope/population: ${spec.set.scopePopulation || "not recorded"}`));
    lines.push(...commentLines(`Time period: ${spec.set.timePeriod || "not recorded"}`));
    lines.push(
      ...commentLines(
        `Direction: ${spec.set.highIsMembership ? "higher raw = more in set" : "inverted"}`,
      ),
    );
    lines.push(...commentLines(`Missing policy: ${JSON.stringify(spec.missing)}`));
    const readiness = calibrationReadiness(spec, meta.type);
    lines.push(
      ...commentLines(
        `Decision status: ${effectiveStatus(spec, meta.type)} (recorded: ${spec.status}); protocol ready: ${readiness.protocolReady ? "yes" : "no"}`,
      ),
    );
    for (const evidence of spec.evidence) {
      const citation = [
        evidence.citation.authors,
        evidence.citation.year,
        evidence.citation.title,
        evidence.citation.doiOrUrl,
        evidence.citation.pages ? `pages ${evidence.citation.pages}` : "",
      ]
        .filter(Boolean)
        .join("; ");
      lines.push(
        ...commentLines(
          `Evidence for ${evidence.supports}: ${citation || "citation not recorded"} — ${evidence.note || "note not recorded"}`,
        ),
      );
    }

    if (meta.type === "raw") lines.push(`${rawName} <- parse_openqca_number(${colRef})`);

    if (
      meta.type === "raw" &&
      (spec.method === "direct" || spec.method === "linear") &&
      fuzzyAnchors
    ) {
      const d = fuzzyAnchors;
      const thresholds = directThresholds(d, spec.set.highIsMembership);
      if (thresholds) {
        lines.push(
          ...commentLines(
            `${spec.method === "linear" ? "Linear" : "Direct"} anchors (full out / crossover / full in): ${d.fullOut} / ${d.crossover} / ${d.fullIn}`,
          ),
        );
        lines.push(...commentLines(`Full out meaning: ${d.meaningFullOut || "not recorded"}`));
        lines.push(...commentLines(`Crossover meaning: ${d.meaningCrossover || "not recorded"}`));
        lines.push(...commentLines(`Full in meaning: ${d.meaningFullIn || "not recorded"}`));
        lines.push(
          `${colRef} <- calibrate(${rawName}, type = "fuzzy", thresholds = c(e=${thresholds[0]}, c=${thresholds[1]}, i=${thresholds[2]}), logistic = ${spec.method === "direct" ? "TRUE" : "FALSE"})`,
        );
        if (!spec.set.highIsMembership) {
          lines.push(`${colRef} <- 1 - ${colRef}  # inverted scale`);
        }
      } else {
        lines.push(...commentLines("Fuzzy calibration anchors are incomplete or unordered; calibration line omitted."));
      }
    } else if (meta.type === "raw" && spec.method === "crisp" && spec.crisp) {
      lines.push(...commentLines(`Inclusion threshold: ${spec.crisp.threshold}`));
      lines.push(...commentLines(`Inclusion meaning: ${spec.crisp.meaningInclusion || "not recorded"}`));
      if (Number.isFinite(spec.crisp.threshold)) {
        if (!spec.set.highIsMembership) {
          lines.push(
            `${colRef} <- ifelse(${rawName} <= ${spec.crisp.threshold}, 1, 0)  # inverted crisp; threshold inclusive`,
          );
        } else {
          lines.push(
            `${colRef} <- calibrate(${rawName}, type = "crisp", thresholds = ${spec.crisp.threshold})`,
          );
        }
      } else {
        lines.push(...commentLines("Crisp threshold is not finite; calibration line omitted."));
      }
    } else if (meta.type === "fuzzy" || meta.type === "crisp") {
      lines.push(`# already calibrated (${meta.type}): ${col}`);
      lines.push(`# Provenance: ${spec.alreadyCalibratedProvenance?.trim() || "not recorded"}`);
      if (!spec.set.highIsMembership) lines.push(`${colRef} <- 1 - ${colRef}  # inverted scale`);
    }

    if (spec.missing.kind === "assign") {
      lines.push(`${colRef}[is.na(${colRef})] <- ${spec.missing.membership}`);
    } else {
      lines.push(`# Missing values for ${col} remain NA and are omitted by complete.cases().`);
    }

    const alternatives = spec.sensitivity?.alternatives ?? [];
    alternatives.forEach((alternative, index) => {
      const altName = `alt_${col.replace(/[^A-Za-z0-9_]/g, "_")}_${index + 1}`;
      lines.push(...commentLines(`Sensitivity alternative: ${alternative.label}`));
      lines.push(...commentLines(`Delta: ${alternative.delta}; rationale: ${alternative.rationale}`));
      if (
        meta.type === "raw" &&
        (spec.method === "direct" || spec.method === "linear") &&
        fuzzyAnchors
      ) {
        const d = fuzzyAnchors;
        const thresholds = directThresholds(d, spec.set.highIsMembership);
        if (thresholds) {
          const gap = Math.max(Math.abs(thresholds[2] - thresholds[0]) * 1e-6, 1e-9);
          const alternativeCrossover = Math.min(
            thresholds[2] - gap,
            Math.max(thresholds[0] + gap, thresholds[1] + alternative.delta),
          );
          lines.push(
            `${altName} <- calibrate(${rawName}, type = "fuzzy", thresholds = c(e=${thresholds[0]}, c=${alternativeCrossover}, i=${thresholds[2]}), logistic = ${spec.method === "direct" ? "TRUE" : "FALSE"})`,
          );
          if (!spec.set.highIsMembership) lines.push(`${altName} <- 1 - ${altName}`);
        } else {
          lines.push(...commentLines("Sensitivity alternative omitted: fuzzy anchors are incomplete or unordered."));
        }
      } else if (
        meta.type === "raw" &&
        spec.method === "crisp" &&
        spec.crisp &&
        Number.isFinite(spec.crisp.threshold)
      ) {
        const alternativeThreshold = spec.crisp.threshold + alternative.delta;
        if (!spec.set.highIsMembership) {
          lines.push(
            `${altName} <- ifelse(${rawName} <= ${alternativeThreshold}, 1, 0)  # inverted crisp; threshold inclusive`,
          );
        } else {
          lines.push(
            `${altName} <- calibrate(${rawName}, type = "crisp", thresholds = ${alternativeThreshold})`,
          );
        }
      } else {
        lines.push(...commentLines("Sensitivity alternative omitted: no complete calibration method is available."));
      }
      if (spec.missing.kind === "assign") {
        lines.push(`${altName}[is.na(${altName})] <- ${spec.missing.membership}`);
      }
    });
    lines.push("");
  }

  if (analysisColumns.length && outcome) {
    const invalidColumns = analysisColumns.filter((column) => invalidActiveRawColumns.has(column));
    if (invalidColumns.length) {
      lines.push(
        ...commentLines(
          `Analysis omitted: active raw calibration is incomplete or invalid for ${invalidColumns.join(", ")}.`,
        ),
      );
    } else {
      const columnVector = rConditions(analysisColumns);
      lines.push(`analysis_df <- df[complete.cases(df[${columnVector}]), , drop = FALSE]`);
      lines.push(`analysis_raw <- raw_data[rownames(analysis_df), , drop = FALSE]`);
      lines.push(
        `tt <- truthTable(analysis_df, outcome = ${rString(outcome)}, conditions = ${rConditions(conditions)},`,
      );
      lines.push(
        `                 incl.cut = ${consCut}, n.cut = ${freqCut}, show.cases = TRUE)`,
      );
      lines.push(`minimize(tt, details = TRUE)                 # complex / conservative`);
      lines.push(`minimize(tt, include = "?", details = TRUE)  # parsimonious`);

      for (const [column, variants] of Object.entries(sensitivity?.variantsByColumn ?? {})) {
        variants.forEach((variant, index) => {
          const thresholds = variant.thresholdsByCondition[column] ?? [];
          const method = variant.methodsByCondition[column];
          if (!method || !thresholds.length) return;
          const variantName = `sensitivity_${rIdentifier(column, "column")}_${index + 1}`;
          const variantFrame = `analysis_${variantName}`;
          const variantRef = rColumnRef(variantFrame, column);
          const rawRef = rColumnRef("analysis_raw", column);
          lines.push(...commentLines(`Computed sensitivity variant: ${variant.label}`));
          lines.push(`${variantFrame} <- analysis_df`);
          if ((method === "direct" || method === "linear") && thresholds.length === 3) {
            lines.push(
              `${variantRef} <- calibrate(parse_openqca_number(${rawRef}), type = "fuzzy", thresholds = c(e=${thresholds[0]}, c=${thresholds[1]}, i=${thresholds[2]}), logistic = ${method === "direct" ? "TRUE" : "FALSE"})`,
            );
            if (variant.highIsMembershipByCondition?.[column] === false) {
              lines.push(`${variantRef} <- 1 - ${variantRef}  # inverted scale`);
            }
          } else if (method === "crisp" && thresholds.length === 1) {
            if (variant.highIsMembershipByCondition?.[column] === false) {
              lines.push(
                `${variantRef} <- ifelse(parse_openqca_number(${rawRef}) <= ${thresholds[0]}, 1, 0)  # inverted crisp; threshold inclusive`,
              );
            } else {
              lines.push(
                `${variantRef} <- calibrate(parse_openqca_number(${rawRef}), type = "crisp", thresholds = ${thresholds[0]})`,
              );
            }
          }
          const variantMissing = variant.missingByCondition?.[column] ?? "NaN";
          if (variantMissing !== "NaN") {
            lines.push(`${variantRef}[is.na(${variantRef})] <- ${variantMissing}`);
          }
          lines.push(
            `tt_${variantName} <- truthTable(${variantFrame}, outcome = ${rString(outcome)}, conditions = ${rConditions(conditions)}, incl.cut = ${consCut}, n.cut = ${freqCut}, show.cases = TRUE)`,
          );
          lines.push(
            `solution_${variantName} <- minimize(tt_${variantName}, include = "?", details = TRUE)`,
          );
          lines.push(`print(solution_${variantName})`);
        });
      }
    }
  }
  if (robustness) {
    const numberVector = (values: number[]): string =>
      values.length ? `c(${values.join(", ")})` : "numeric(0)";
    const robustFreqCuts = [...new Set(robustness.cells.map((cell) => cell.freqCut))].sort((a, b) => a - b);
    const robustConsCuts = [...new Set(robustness.cells.map((cell) => cell.consCut))].sort((a, b) => a - b);
    const robustPriCuts = [...new Set(
      robustness.cells
        .map((cell) => cell.priCut)
        .filter((cut): cut is number => cut !== null),
    )].sort((a, b) => a - b);
    const scenarioLabels = [...new Set(robustness.cells.map((cell) => cell.scenarioLabel))];
    lines.push(...commentLines(
      `Combined robustness grid recorded ${robustness.totalCells} cells across scenarios: ${scenarioLabels.join(" | ")}.`,
    ));
    lines.push("# The loop below re-runs the analytical cutoff grid on the base calibrated frame.");
    lines.push("# Named anchor alternatives are emitted above as sensitivity_* frames; their complete");
    lines.push("# scenario-by-cutoff classifications remain in the JSON/Markdown exports.");
    lines.push(`robustness_freq_cuts <- ${numberVector(robustFreqCuts)}`);
    lines.push(`robustness_cons_cuts <- ${numberVector(robustConsCuts)}`);
    lines.push("for (n_cut in robustness_freq_cuts) {");
    lines.push("  for (incl_cut in robustness_cons_cuts) {");
    lines.push(
      `    tt_robust <- truthTable(analysis_df, outcome = ${rString(outcome)}, conditions = ${rConditions(conditions)}, incl.cut = incl_cut, n.cut = n_cut, show.cases = TRUE)`,
    );
    lines.push("    print(minimize(tt_robust, include = \"?\", details = TRUE))");
    lines.push("  }");
    lines.push("}");
    if (robustPriCuts.length) {
      lines.push(`robustness_pri_cuts <- ${numberVector(robustPriCuts)}`);
      lines.push("for (n_cut in robustness_freq_cuts) {");
      lines.push("  for (incl_cut in robustness_cons_cuts) {");
      lines.push("    for (pri_cut in robustness_pri_cuts) {");
      lines.push(
        `      tt_robust_pri <- truthTable(analysis_df, outcome = ${rString(outcome)}, conditions = ${rConditions(conditions)}, incl.cut = incl_cut, n.cut = n_cut, pri.cut = pri_cut, show.cases = TRUE)`,
      );
      lines.push("      print(minimize(tt_robust_pri, include = \"?\", details = TRUE))");
      lines.push("    }");
      lines.push("  }");
      lines.push("}");
    }
  }

    lines.push("sessionInfo()");
  return lines.join("\n");
}

export function buildCalibrationProtocolJson(args: {
  ds: RawDataset;
  calibSpecs: CalibSpecs;
  varMeta: Record<string, VarMeta>;
  conditions: string[];
  outcome: string;
  freqCut: number;
  consCut: number;
  evaluation?: CalibrationEvaluation;
  sensitivity?: SensitivityBundle;
  robustness?: CombinedRobustnessResult | null;
  sensitivitySummary?: CalibrationSensitivityResultWithRows[] | null;
  extraLimitations?: string;
}): object {
  const sets = Object.values(args.calibSpecs).filter((spec) => {
    const role = args.varMeta[spec.column]?.role;
    return role === "condition" || role === "outcome";
  });
  const decisionDetails = sets.map((spec) => {
    const varType = args.varMeta[spec.column]?.type ?? "raw";
    const readiness = calibrationReadiness(spec, varType);
    return {
      column: spec.column,
      role: args.varMeta[spec.column]?.role,
      status: spec.status,
      effectiveStatus: effectiveStatus(spec, varType),
      protocolReady: readiness.protocolReady,
      missingFields: readiness.missingFields,
      missingEvidence: readiness.missingEvidence,
      methodConfirmed: spec.methodConfirmed,
      caseReviewConfirmed: spec.caseReviewConfirmed,
      externalReview: spec.externalReview ?? null,
      sensitivityReviewed: spec.sensitivity.reviewed,
      sensitivityAlternatives: spec.sensitivity.alternatives,
    };
  });
  const provisional = decisionDetails
    .filter((decision) => decision.effectiveStatus === "provisional")
    .map((decision) => decision.column);
  const unresolved = decisionDetails
    .filter((decision) => decision.effectiveStatus === "unresolved")
    .map((decision) => decision.column);
  const transformations = args.evaluation
    ? args.ds.rows.map((row, rowIndex) => {
        const caseLabel = String(row[args.ds.caseCol] ?? "");
        const cells = args.evaluation!.cells.filter((cell) => cell.rowIndex === rowIndex);
        return {
          rowIndex,
          caseLabel,
          columns: Object.fromEntries(
            cells.map((cell) => [
              cell.column,
              {
                rawValue: cell.rawValue,
                membership: cell.membership,
                side: cell.side,
                flags: cell.flags,
              },
            ]),
          ),
        };
      })
    : [];

  return {
    tool: "openQCA",
    toolVersion: TOOL_VERSION,
    exportedAt: new Date().toISOString(),
    methodologyReferences: METHODOLOGY_REFERENCES,
    dataset: args.ds.name,
    engine: {
      calibration:
        "direct logistic Ragin 2008 (log-odds ±3 at anchors ≈0.0474/0.5/0.9526); linear fuzzy is piecewise linear between the same three anchors (QCA::calibrate logistic=FALSE); crisp threshold inclusive (>= for higher-membership scales, <= for inverted scales)",
      missingValues: "spec.missing is applied before cases enter the analysis",
    },
    sets,
    decisions: decisionDetails,
    transformations,
    analysis: {
      conditions: args.conditions,
      outcome: args.outcome,
      freqCut: args.freqCut,
      consCut: args.consCut,
    },
    sensitivity: args.sensitivity ?? null,
    sensitivitySummary:
      args.sensitivitySummary ?? Object.values(args.sensitivity?.resultsByColumn ?? {}).flat(),
    robustness: args.robustness ?? null,
    limitations: [
      "Set membership is a research judgment; openQCA records rationale but does not certify substantive validity.",
      "Empirical distribution diagnostics are aids, not proof of anchors.",
      "Outcome membership is distinct from truth-table frequency/consistency/PRI cutoffs and solution fit.",
      provisional.length
        ? `Provisional decisions: ${provisional.join(", ")}.`
        : "No columns marked provisionally sourced at export.",
      unresolved.length
        ? `Unresolved decisions: ${unresolved.join(", ")}.`
        : "No columns remain unresolved at export.",
      args.extraLimitations?.trim() || "",
    ]
      .filter(Boolean)
      .join(" "),
  };
}

const EVIDENCE_TYPE_KEYS: Record<EvidenceType, DictKey> = {
  literature: "calib.evidence.type.literature",
  theory: "calib.evidence.type.theory",
  standard: "calib.evidence.type.standard",
  domain_expertise: "calib.evidence.type.domain_expertise",
  case_knowledge: "calib.evidence.type.case_knowledge",
  empirical_diagnostic: "calib.evidence.type.empirical_diagnostic",
};

const EVIDENCE_TARGET_KEYS: Record<EvidenceTarget, DictKey> = {
  set: "calib.evidence.target.set",
  method: "calib.evidence.target.method",
  fullOut: "calib.evidence.target.fullOut",
  crossover: "calib.evidence.target.crossover",
  fullIn: "calib.evidence.target.fullIn",
  threshold: "calib.evidence.target.threshold",
};

const CASE_SIDE_KEYS: Record<string, DictKey> = {
  in: "calib.side.in",
  out: "calib.side.out",
  half: "calib.side.half",
  missing: "calib.side.missing",
};

const CASE_FLAG_KEYS: Record<string, DictKey> = {
  missing: "calib.flag.missing",
  excluded: "calib.flag.excluded",
  unresolved: "calib.flag.unresolved",
  "missing-assigned": "calib.flag.missingAssigned",
  "raw-anchor-boundary": "calib.flag.rawBoundary",
  "exact-crossover": "calib.flag.exactCrossover",
  "near-crossover": "calib.flag.nearCrossover",
  "duplicate-case-label": "calib.flag.duplicateCase",
  "out-of-range": "calib.flag.outOfRange",
  "missing-spec": "calib.flag.missingSpec",
  "missing-method": "calib.flag.missingMethod",
  "invalid-parameters": "calib.flag.invalidParameters",
};

function protocolSideLabel(locale: "de" | "en", side: string): string {
  return t(locale, CASE_SIDE_KEYS[side] ?? "calib.side.missing");
}

function protocolFlagLabel(locale: "de" | "en", flag: string): string {
  return t(locale, CASE_FLAG_KEYS[flag] ?? "calib.flag.other");
}

const MISSING_FIELD_KEYS: Record<string, DictKey> = {
  setLabel: "calib.set.label",
  definition: "proto.definition",
  unit: "proto.unit",
  scopePopulation: "proto.scope",
  timePeriod: "proto.timePeriod",
  directAnchors: "calib.anchors.title",
  crispThreshold: "calib.crisp.threshold",
  alreadyCalibratedProvenance: "proto.provenance",
  method: "calib.method.title",
  missingPolicy: "proto.missingPolicy",
  meaningFullOut: "proto.anchor.fullOut",
  meaningCrossover: "proto.anchor.crossover",
  meaningFullIn: "proto.anchor.fullIn",
  meaningInclusion: "proto.anchor.inclusion",
  methodConfirmed: "proto.methodConfirmed",
  caseReviewConfirmed: "proto.caseReviewConfirmed",
  provisionalDefaults: "proto.status",
  sensitivityReview: "proto.sensitivityReviewConfirmed",
};

function protocolStatusKey(status: CalibrationDecisionStatus): DictKey {
  if (status === "provisional") return "calib.status.provisional";
  if (status === "sourced") return "calib.status.sourced";
  if (status === "externally_checked") return "calib.status.external";
  return "calib.status.unresolved";
}

function missingPolicyLabel(
  locale: "de" | "en",
  spec: CalibrationSpec,
): string {
  if (spec.missing.kind === "exclude_case") return t(locale, "calib.missing.exclude");
  if (spec.missing.kind === "leave_unresolved") return t(locale, "calib.missing.unresolved");
  return `${t(locale, "calib.missing.assign")}: ${spec.missing.membership}`;
}

function fmtEvidence(spec: CalibrationSpec, locale: "de" | "en"): string {
  if (!spec.evidence.length) return t(locale, "proto.noEvidence");
  return spec.evidence
    .map((e, i) => {
      const cit = [
        e.citation.authors,
        e.citation.year,
        e.citation.title,
        e.citation.doiOrUrl,
        e.citation.pages ? `pp. ${e.citation.pages}` : "",
      ]
        .filter(Boolean)
        .join(". ");
      const aid =
        e.type === "empirical_diagnostic" || !e.isSubstantive
          ? t(locale, "proto.evidenceAid")
          : "";
      return `${i + 1}. **${t(locale, EVIDENCE_TYPE_KEYS[e.type])}** (${t(locale, "calib.evidence.supports")}: ${t(locale, EVIDENCE_TARGET_KEYS[e.supports])})${aid}\n   ${cit}\n   ${e.note}`;
    })
    .join("\n");
}

export function buildCalibrationNarrative(args: {
  ds: RawDataset;
  calibSpecs: CalibSpecs;
  varMeta: Record<string, VarMeta>;
  conditions: string[];
  outcome: string;
  freqCut: number;
  consCut: number;
  sensitivitySummary?: CalibrationSensitivityResultWithRows[] | null;
  evaluation?: CalibrationEvaluation;
  sensitivity?: SensitivityBundle;
  robustness?: CombinedRobustnessResult | null;
  locale?: "de" | "en";
}): string {
  const locale = args.locale ?? "de";
  const en = locale === "en";
  const lines: string[] = [];
  lines.push(en ? "# Calibration protocol (openQCA)" : "# Kalibrierungsprotokoll (openQCA)");
  lines.push("");
  lines.push(
    en
      ? `Dataset: **${args.ds.name}**. Software: openQCA ${TOOL_VERSION}. Exported: ${new Date().toISOString()}.`
      : `Datensatz: **${args.ds.name}**. Software: openQCA ${TOOL_VERSION}. Exportiert: ${new Date().toISOString()}.`,
  );
  lines.push("");
  lines.push(
    en
      ? "## Method (engine)"
      : "## Methode (Rechenkern)",
  );
  lines.push(
    en
      ? "Direct fuzzy calibration follows Ragin (2008), *Redesigning Social Inquiry* (DOI 10.7208/chicago/9780226702797.001.0001): logistic mapping with qualitative anchors for full non-membership, crossover (0.5), and full membership. Engine fixed points at anchors use log-odds ±3 (≈0.0474 / 0.50 / 0.9526). Linear fuzzy calibration uses the same three qualitative anchors with a piecewise-linear mapping and is exported as QCA::calibrate(logistic = FALSE). Crisp calibration uses an inclusive threshold (≥ → 1 for higher-membership scales; ≤ → 1 for inverted scales). See also Schneider & Wagemann (2012), pp. 35–36; Oana & Schneider (2022), *A Robustness Test for Qualitative Comparative Analysis (QCA)*, pp. 603–638, DOI 10.1177/00491241211036158; R package QCA `calibrate()` (Duša)."
      : "Direkte Fuzzy-Kalibrierung nach Ragin (2008), *Redesigning Social Inquiry* (DOI 10.7208/chicago/9780226702797.001.0001): logistische Abbildung mit qualitativen Ankern für volle Nicht-Zugehörigkeit, Kreuzung (0,5) und volle Zugehörigkeit. Engine-Fixpunkte an den Ankern nutzen Log-Odds ±3 (≈0,0474 / 0,50 / 0,9526). Lineare Fuzzy-Kalibrierung nutzt dieselben drei qualitativen Anker mit einer stückweise linearen Abbildung und wird als QCA::calibrate(logistic = FALSE) exportiert. Crisp: inklusive Schwelle (≥ → 1 bei aufsteigender Zugehörigkeit; ≤ → 1 bei invertierter Skala). Siehe Schneider & Wagemann (2012), S. 35–36; Oana & Schneider (2022), *A Robustness Test for Qualitative Comparative Analysis (QCA)*, S. 603–638, DOI 10.1177/00491241211036158; R-Paket QCA `calibrate()` (Duša).",
  );
  lines.push("");
  lines.push(en ? "### Methodology references" : "### Methodologische Referenzen");
  for (const reference of METHODOLOGY_REFERENCES) {
    lines.push(
      `- ${reference.citation}${reference.pages ? `, pp. ${reference.pages}` : ""}. ${reference.scope}. ${reference.doi ? `DOI: ${reference.doi}. ` : ""}${reference.url}`,
    );
  }
  lines.push("");
  lines.push(
    en
      ? `Analysis cutoffs (not outcome membership): frequency n.cut = ${args.freqCut}, consistency incl.cut = ${args.consCut}. Conditions: ${args.conditions.join(", ") || "—"}. Outcome: ${args.outcome || "—"}.`
      : `Analyse-Cutoffs (nicht Outcome-Zugehörigkeit): Frequenz n.cut = ${args.freqCut}, Konsistenz incl.cut = ${args.consCut}. Bedingungen: ${args.conditions.join(", ") || "—"}. Outcome: ${args.outcome || "—"}.`,
  );
  lines.push("");

  const cols = Object.keys(args.varMeta).filter((c) => {
    const r = args.varMeta[c]?.role;
    return r === "condition" || r === "outcome";
  });

  for (const col of cols) {
    const spec = args.calibSpecs[col] ?? null;
    const meta = args.varMeta[col];
    if (!spec || !meta) continue;
    const fuzzyAnchors =
      spec.method === "direct" ? spec.direct : spec.method === "linear" ? spec.linear : undefined;
    const role = t(
      locale,
      meta.role === "outcome" ? "calib.guide.role.outcome" : "calib.guide.role.condition",
    );
    lines.push(`## ${spec.set.setLabel || col} (${role}: \`${col}\`)`);
    lines.push("");
    const readiness = calibrationReadiness(spec, meta.type);
    const missingFields = readiness.missingFields
      .map((field) => t(locale, MISSING_FIELD_KEYS[field] ?? "proto.missingText"))
      .join(", ");
    const missingEvidence = readiness.missingEvidence
      .map((target) => t(locale, EVIDENCE_TARGET_KEYS[target]))
      .join(", ");
    const readinessDetails = [
      readiness.protocolReady ? t(locale, "proto.ready") : t(locale, "proto.setNotReady"),
      missingFields ? `${t(locale, "proto.missingFields")}: ${missingFields}` : "",
      missingEvidence ? `${t(locale, "proto.missingEvidence")}: ${missingEvidence}` : "",
    ]
      .filter(Boolean)
      .join("; ");
    const yesNo = (value: boolean) => t(locale, value ? "proto.yes" : "proto.no");
    lines.push(
      `- **${t(locale, "proto.status")}:** ${t(locale, protocolStatusKey(effectiveStatus(spec, meta.type)))} (${t(locale, "proto.recorded")}: ${t(locale, protocolStatusKey(spec.status))})`,
    );
    lines.push(`- **${readinessDetails}**`);
    lines.push(
      `- **${t(locale, "proto.definition")}:** ${spec.set.definition || `_${t(locale, "proto.missingText")}_`}`,
    );
    lines.push(`- **${t(locale, "proto.unit")}:** ${spec.set.unit || "—"}`);
    lines.push(`- **${t(locale, "proto.scope")}:** ${spec.set.scopePopulation || "—"}`);
    lines.push(`- **${t(locale, "proto.timePeriod")}:** ${spec.set.timePeriod || "—"}`);
    lines.push(
      `- **${t(locale, "proto.direction")}:** ${t(
        locale,
        spec.set.highIsMembership ? "proto.direction.high" : "proto.direction.low",
      )}`,
    );
    lines.push(`- **${t(locale, "proto.missingPolicy")}:** ${missingPolicyLabel(locale, spec)}`);
    lines.push(`- **${t(locale, "proto.setNotes")}:** ${spec.set.notes || "—"}`);
    lines.push(
      `- **${t(locale, "proto.methodConfirmed")}:** ${yesNo(spec.methodConfirmed)}`,
    );
    lines.push(
      `- **${t(locale, "proto.caseReviewConfirmed")}:** ${yesNo(spec.caseReviewConfirmed)}`,
    );
    lines.push(
      `- **${t(locale, "proto.sensitivityReviewConfirmed")}:** ${yesNo(spec.sensitivity.reviewed)}`,
    );

    if (
      meta.type === "raw" &&
      (spec.method === "direct" || spec.method === "linear") &&
      fuzzyAnchors
    ) {
      const d = fuzzyAnchors;
      lines.push(
        `- **${t(locale, spec.method === "linear" ? "proto.method.linear" : "proto.method.direct")}:**`,
      );
      lines.push(
        `- **${t(locale, "calib.anchors.raw")}:** ${t(locale, "calib.handle.out")} = ${d.fullOut}; ${t(locale, "calib.handle.cross")} = ${d.crossover}; ${t(locale, "calib.handle.in")} = ${d.fullIn}`,
      );
      lines.push(
        `  - ${t(locale, "proto.anchor.fullOut")}: ${d.meaningFullOut || "—"}`,
      );
      lines.push(
        `  - ${t(locale, "proto.anchor.crossover")}: ${d.meaningCrossover || "—"}`,
      );
      lines.push(
        `  - ${t(locale, "proto.anchor.fullIn")}: ${d.meaningFullIn || "—"}`,
      );
    } else if (meta.type === "raw" && spec.method === "crisp" && spec.crisp) {
      lines.push(`- **${t(locale, "proto.method.crisp")}:**`);
      lines.push(`- **${t(locale, "calib.crisp.threshold")}:** ${spec.crisp.threshold}`);
      lines.push(
        `  - ${t(locale, "proto.anchor.inclusion")}: ${spec.crisp.meaningInclusion || "—"}`,
      );
    } else {
      lines.push(`- **${t(locale, "proto.method.already")}:** (${meta.type})`);
      lines.push(
        `- **${t(locale, "proto.provenance")}:** ${spec.alreadyCalibratedProvenance || "—"}`,
      );
    }
    if (spec.sensitivity.alternatives.length) {
      lines.push(en ? "### Named sensitivity alternatives" : "### Benannte Sensitivitätsalternativen");
      for (const alternative of spec.sensitivity.alternatives) {
        lines.push(
          `- **${alternative.label || t(locale, "proto.missingText")}:** Δ = ${alternative.delta}; ${alternative.rationale || t(locale, "proto.missingText")}`,
        );
      }
      lines.push("");
    }

    if (spec.exceptionalCases.length) {
      lines.push(`- **${t(locale, "proto.exceptionalCases")}:**`);
      for (const ex of spec.exceptionalCases) {
        const rowSuffix =
          typeof ex.rowIndex === "number"
            ? ` (${t(locale, "proto.row")} ${ex.rowIndex + 1})`
            : "";
        lines.push(`  - ${ex.caseLabel}${rowSuffix}: ${ex.note}`);
      }
    }

    lines.push("");
    lines.push(en ? "### Evidence" : "### Evidenz");
    lines.push(fmtEvidence(spec, locale));
    lines.push("");
  }

  if (args.evaluation) {
    lines.push(en ? "## Case-level transformations" : "## Fallbezogene Transformationen");
    lines.push("");
    for (const [rowIndex, row] of args.ds.rows.entries()) {
      const caseLabel = String(row[args.ds.caseCol] ?? "");
      const cells = args.evaluation.cells.filter((cell) => cell.rowIndex === rowIndex);
      lines.push(`- **${caseLabel}** (${t(locale, "proto.row")} ${rowIndex + 1}):`);
      for (const cell of cells) {
        lines.push(
          `  - \`${cell.column}\`: ${t(locale, "calib.cases.raw")} = ${cell.rawValue ?? t(locale, "proto.missingText")} → ${t(locale, "calib.cases.m")} = ${cell.membership ?? t(locale, "proto.missingText")}; ${t(locale, "calib.cases.side")} = ${protocolSideLabel(locale, cell.side)}; ${t(locale, "calib.cases.flags")} = ${cell.flags.map((flag) => protocolFlagLabel(locale, flag)).join(", ") || t(locale, "proto.none")}`,
        );
      }
    }
    lines.push("");
  }

  const sensitivityResults =
    args.sensitivitySummary?.length
      ? args.sensitivitySummary
      : Object.values(args.sensitivity?.resultsByColumn ?? {}).flat();
  if (sensitivityResults.length) {
    lines.push(en ? "## Calibration sensitivity" : "## Kalibrierungs-Sensitivität");
    lines.push("");
    for (const s of sensitivityResults) {
      const focusColumn = Object.keys(args.sensitivity?.resultsByColumn ?? {}).find((column) =>
        args.sensitivity?.resultsByColumn[column]?.some((result) => result.variantId === s.variantId),
      );
      const baseSpec = focusColumn ? args.calibSpecs[focusColumn] : undefined;
      const baseFuzzyAnchors =
        baseSpec?.method === "direct"
          ? baseSpec.direct
          : baseSpec?.method === "linear"
            ? baseSpec.linear
            : undefined;
      const baseThresholds =
        baseFuzzyAnchors
          ? directThresholds(baseFuzzyAnchors, baseSpec!.set.highIsMembership) ?? []
          : baseSpec?.method === "crisp" && baseSpec.crisp
            ? [baseSpec.crisp.threshold]
            : [];
      lines.push(`### ${s.label} (\`${s.variantId}\`)`);
      lines.push(
        `- ${t(locale, "calib.sens.membershipChanges")}: ${s.flips.length}; ${t(locale, "calib.sens.half")}: ${s.flips.filter((f) => f.crossedHalf).length}`,
      );
      lines.push(
        `- ${t(locale, "calib.sens.truthChanges")}: ${s.truthTableRowChanges.length}; ${t(locale, "calib.sens.caseChanges")}: ${s.caseClassificationChanges.length}`,
      );
      lines.push(
        `- ${t(locale, "calib.sens.thresholds")}: ${t(locale, "calib.sens.baseSol")} = \`${JSON.stringify(baseThresholds)}\`; ${t(locale, "calib.sens.varSol")} = \`${JSON.stringify(s.variantThresholdsByCondition)}\``,
      );
      lines.push(
        `- ${t(locale, "calib.sens.fit")}: ${t(locale, "calib.sens.baseFit", { cons: s.baseFit.consistency.toFixed(3), cov: s.baseFit.coverage.toFixed(3) })}; ${t(locale, "calib.sens.variantFit", { cons: s.variantFit.consistency.toFixed(3), cov: s.variantFit.coverage.toFixed(3) })}`,
      );
      lines.push(
        `- ${t(locale, "calib.sens.solChanged")}: ${t(locale, s.solutionChanged ? "proto.yes" : "proto.no")}`,
      );
      lines.push(`- ${t(locale, "calib.sens.baseSol")}: \`${s.baseSolutionExpression || "—"}\``);
      lines.push(`- ${t(locale, "calib.sens.varSol")}: \`${s.variantSolutionExpression || "—"}\``);
      if (s.truthTableRowChanges.length) {
        lines.push(`- ${t(locale, "proto.sensitivity.truthRows")}`);
        for (const change of s.truthTableRowChanges.slice(0, 8)) {
          lines.push(
            `  - ${change.caseLabel} (${t(locale, "proto.row")} ${change.rowIndex + 1}): ${change.baseBits} → ${change.variantBits}`,
          );
        }
      }
      if (s.caseClassificationChanges.length) {
        lines.push(`- ${t(locale, "proto.sensitivity.caseRows")}`);
        for (const change of s.caseClassificationChanges.slice(0, 8)) {
          const sideLabel = (side: string) =>
            side === "in"
              ? t(locale, "calib.side.in")
              : side === "out"
                ? t(locale, "calib.side.out")
                : side === "half"
                  ? t(locale, "calib.side.half")
                  : t(locale, "calib.side.missing");
          lines.push(
            `  - ${t(locale, "calib.sens.caseChange", {
              caseLabel: `${change.caseLabel} (${t(locale, "proto.row")} ${change.rowIndex + 1})`,
              baseBits: change.base.conditionBits,
              variantBits: change.variant.conditionBits,
              baseOutcome: sideLabel(change.base.outcomeSide),
              variantOutcome: sideLabel(change.variant.outcomeSide),
              baseRow: change.base.rowOutput ?? t(locale, "proto.missingText"),
              variantRow: change.variant.rowOutput ?? t(locale, "proto.missingText"),
            })}`,
          );
        }
      }
      lines.push("");
    }
  }
  if (args.robustness) {
    const robustness = args.robustness;
    const formatNumber = (value: number | null): string =>
      value === null ? "—" : Number.isFinite(value) ? value.toFixed(3) : "—";
    const displayCaseLabel = (value: string): string => {
      try {
        const parsed = JSON.parse(value) as unknown;
        return Array.isArray(parsed) && typeof parsed[0] === "string" ? parsed[0] : value;
      } catch {
        return value;
      }
    };
    lines.push(en ? "## Combined robustness" : "## Kombinierte Robustheit");
    lines.push("");
    lines.push(
      en
        ? `The grid contains ${robustness.totalCells} cells across explicit calibration scenarios and frequency, consistency, and PRI cutoffs. The baseline is \`${robustness.baseline.scenarioId}\` with n.cut = ${robustness.baseline.freqCut}, incl.cut = ${robustness.baseline.consCut}, PRI = ${formatNumber(robustness.baseline.priCut)}.`
        : `Das Raster enthält ${robustness.totalCells} Zellen über explizite Kalibrierungsszenarien sowie Frequenz-, Konsistenz- und PRI-Cutoffs. Die Basis ist \`${robustness.baseline.scenarioId}\` mit n.cut = ${robustness.baseline.freqCut}, incl.cut = ${robustness.baseline.consCut}, PRI = ${formatNumber(robustness.baseline.priCut)}.`,
    );
    lines.push("");
    lines.push(en ? "### Solution-term stability" : "### Stabilität der Lösungsterme");
    for (const type of ["complex", "intermediate", "parsimonious"] as const) {
      const entries = robustness.solutionStability.filter((entry) => entry.type === type).slice(0, 3);
      for (const entry of entries) {
        lines.push(
          `- ${type}: \`${entry.expression || "—"}\` — ${entry.cells}/${robustness.totalCells} (${formatNumber(entry.share)})`,
        );
      }
    }
    lines.push("");
    const changedCases = robustness.caseStability.filter((entry) => entry.changedCells > 0);
    lines.push(en ? "### Case-oriented changes" : "### Fallbezogene Änderungen");
    if (!changedCases.length) {
      lines.push(en ? "- No case classification changes relative to the baseline cell." : "- Keine Fallklassifikationsänderung gegenüber der Basiszelle.");
    } else {
      for (const entry of changedCases.slice(0, 20)) {
        lines.push(
          `- ${displayCaseLabel(entry.caseLabel)}: ${entry.changedCells}/${entry.observedCells} cells changed (${formatNumber(entry.changeShare)}); status = ${entry.status}`,
        );
      }
    }
    lines.push("");
    lines.push(en ? "### Grid cells" : "### Rasterzellen");
    for (const cell of robustness.cells) {
      lines.push(
        `- ${cell.scenarioLabel}: n.cut = ${cell.freqCut}, incl.cut = ${cell.consCut}, PRI = ${formatNumber(cell.priCut)}; parsimonious = \`${cell.solutions.parsimonious.expression || "—"}\`; changed cases = ${cell.caseClassificationChanges.length}`,
      );
    }
    lines.push("");
  }

  lines.push(en ? "## Limitations" : "## Grenzen");
  lines.push(
    en
      ? "This protocol documents decisions and software transformations. It does not replace peer review of substantive set definitions. Linear and four-value methods are available in the engine but not used in this guided export path unless recorded above."
      : "Dieses Protokoll dokumentiert Entscheidungen und Software-Transformationen. Es ersetzt keine fachliche Prüfung der Set-Definitionen. Lineare und Vier-Werte-Methoden existieren im Rechenkern, werden im geführten Exportpfad nur genutzt, wenn oben vermerkt.",
  );
  lines.push("");

  return lines.join("\n");
}

export function downloadText(filename: string, text: string, mime: string) {
  const blob = new Blob([text], { type: mime });
  const link = document.createElement("a");
  link.href = URL.createObjectURL(blob);
  link.download = filename;
  link.click();
  URL.revokeObjectURL(link.href);
}
